name: OSS
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{secrets.AccessKey_ID}}
          access-key-secret: ${{secrets.Access_Key_Secret}}
      - run: ossutil cp -rf dist oss://jx3box/static/jx3box-lib/
